# Generated by Django 3.0.7 on 2020-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(max_length=3000, verbose_name='変換元')),
                ('target_text', models.CharField(max_length=3000, verbose_name='変換後')),
            ],
        ),
    ]
